def num_render_ahead_frames() -> int: ...
def current_frame() -> int: ...
def width() -> int: ...
def height() -> int: ...
def time() -> float: ...
def delta_time() -> float: ...

class AttachmentInfo:
	def __init__(self, format: int, beginState: int, inUseState: int, endState: int, usage: int, stencilUsage: int, msaaLevel: int): ...

class SubpassInfo:
	def __init__(self, inputs: list[int], color_ouputs: list[int], depth_stencil_couput: int, preserves: list[int]): ...

class DependencyInfo:
	def __init__(self, source: int, dest: int, source_stage: int, dest_stage: int, source_access: int, dest_access: int): ...

class FrameBuffer:
	def __init__(self, render_pass: RenderPass, attachments: list[Texture], width: int, height: int): ...
	def close() -> None: ...

class RenderPass:
	def __init__(self, attachments: list[AttachmentInfo], subpasses: list[SubpassInfo], dependencies: list[DependencyInfo]): ...
	def close() -> None: ...
	def begin(frame_buffer: FrameBuffer, clear_values: list) -> None: ...
	def next_subpass() -> None: ...
	def end() -> None: ...

class Texture:
	def __init__(self, format: int, usage: int, aspect: int, width: int, height: int, samples: int): ...
	def close() -> None: ...